export const courseProgressData = [
  {
    id: 1,
    courseName: "Introduction to JavaScript",
    courseNumber: 1,
    completePercentage: 20,
  },
  {
    id: 2,
    courseName: "HTML and CSS Basics",
    courseNumber: 2,
    completePercentage: 40,
  },
  {
    id: 3,
    courseName: "React.js Fundamentals",
    courseNumber: 3,
    completePercentage: 60,
  },
  {
    id: 4,
    courseName: "Node.js and Express",
    courseNumber: 4,
    completePercentage: 80,
  },
  {
    id: 5,
    courseName: "Full-Stack Web Development",
    courseNumber: 5,
    completePercentage: 100,
  },
  {
    id: 6,
    courseName: "Python Basics",
    courseNumber: 6,
    completePercentage: 10,
  },
  {
    id: 7,
    courseName: "Data Structures and Algorithms",
    courseNumber: 7,
    completePercentage: 30,
  },
  {
    id: 8,
    courseName: "Database Design and Management",
    courseNumber: 8,
    completePercentage: 15,
  },
  {
    id: 9,
    courseName: "Introduction to Machine Learning",
    courseNumber: 9,
    completePercentage: 55,
  },
  {
    id: 10,
    courseName: "Artificial Intelligence Ethics",
    courseNumber: 10,
    completePercentage: 50,
  },
  {
    id: 11,
    courseName: "Software Architecture",
    courseNumber: 11,
    completePercentage: 70,
  },
  {
    id: 12,
    courseName: "Data Science and Visualization",
    courseNumber: 12,
    completePercentage: 90,
  },
  {
    id: 13,
    courseName: "Introduction to Cybersecurity",
    courseNumber: 13,
    completePercentage: 55,
  },
  {
    id: 14,
    courseName: "Network Administration",
    courseNumber: 14,
    completePercentage: 75,
  },
  {
    id: 15,
    courseName: "Software Testing and QA",
    courseNumber: 15,
    completePercentage: 35,
  },
  {
    id: 16,
    courseName: "Cloud Computing",
    courseNumber: 16,
    completePercentage: 85,
  },
  {
    id: 17,
    courseName: "Introduction to Blockchain",
    courseNumber: 17,
    completePercentage: 65,
  },
  {
    id: 18,
    courseName: "Internet of Things (IoT)",
    courseNumber: 18,
    completePercentage: 45,
  },
  {
    id: 19,
    courseName: "Applied Robotics",
    courseNumber: 19,
    completePercentage: 5,
  },
  {
    id: 20,
    courseName: "Embedded Systems",
    courseNumber: 20,
    completePercentage: 95,
  },
  {
    id: 21,
    courseName: "Android App Development",
    courseNumber: 21,
    completePercentage: 70,
  },
  {
    id: 22,
    courseName: "iOS App Development",
    courseNumber: 22,
    completePercentage: 50,
  },
  {
    id: 23,
    courseName: "Frontend Web Frameworks",
    courseNumber: 23,
    completePercentage: 25,
  },
  {
    id: 24,
    courseName: "Backend Web Frameworks",
    courseNumber: 24,
    completePercentage: 45,
  },
  {
    id: 25,
    courseName: "Software Engineering Principles",
    courseNumber: 25,
    completePercentage: 80,
  },
  {
    id: 26,
    courseName: "Agile Development Methodology",
    courseNumber: 26,
    completePercentage: 60,
  },
  {
    id: 27,
    courseName: "Project Management",
    courseNumber: 27,
    completePercentage: 90,
  },
  {
    id: 28,
    courseName: "Data Analytics",
    courseNumber: 28,
    completePercentage: 15,
  },
  {
    id: 29,
    courseName: "Business Intelligence",
    courseNumber: 29,
    completePercentage: 35,
  },
  {
    id: 30,
    courseName: "Digital Marketing",
    courseNumber: 30,
    completePercentage: 65,
  },
  {
    id: 31,
    courseName: "User Experience (UX) Design",
    courseNumber: 31,
    completePercentage: 40,
  },
  {
    id: 32,
    courseName: "Graphics and Motion Design",
    courseNumber: 32,
    completePercentage: 20,
  },
  {
    id: 33,
    courseName: "Video Editing",
    courseNumber: 33,
    completePercentage: 10,
  },
  {
    id: 34,
    courseName: "Photography Fundamentals",
    courseNumber: 34,
    completePercentage: 50,
  },
  {
    id: 35,
    courseName: "Audio Production",
    courseNumber: 35,
    completePercentage: 70,
  },
  {
    id: 36,
    courseName: "Game Development with Unity",
    courseNumber: 36,
    completePercentage: 30,
  },
  {
    id: 37,
    courseName: "Virtual Reality (VR) Development",
    courseNumber: 37,
    completePercentage: 85,
  },
  {
    id: 38,
    courseName: "Artificial Intelligence in Games",
    courseNumber: 38,
    completePercentage: 55,
  },
  {
    id: 39,
    courseName: "Augmented Reality (AR) Apps",
    courseNumber: 39,
    completePercentage: 75,
  },
  {
    id: 40,
    courseName: "Data Privacy and Security",
    courseNumber: 40,
    completePercentage: 95,
  },
  {
    id: 41,
    courseName: "Ethical Hacking and Penetration Testing",
    courseNumber: 41,
    completePercentage: 60,
  },
  {
    id: 42,
    courseName: "Network Security",
    courseNumber: 42,
    completePercentage: 20,
  },
  {
    id: 43,
    courseName: "Cryptography",
    courseNumber: 43,
    completePercentage: 40,
  },
  {
    id: 44,
    courseName: "Digital Forensics",
    courseNumber: 44,
    completePercentage: 85,
  },
  {
    id: 45,
    courseName: "Internet Security and Privacy",
    courseNumber: 45,
    completePercentage: 30,
  },
  {
    id: 46,
    courseName: "Cloud Security",
    courseNumber: 46,
    completePercentage: 50,
  },
  {
    id: 47,
    courseName: "Cybersecurity Governance",
    courseNumber: 47,
    completePercentage: 65,
  },
  {
    id: 48,
    courseName: "Machine Learning Applications",
    courseNumber: 48,
    completePercentage: 70,
  },
  {
    id: 49,
    courseName: "Artificial Intelligence in Healthcare",
    courseNumber: 49,
    completePercentage: 90,
  },
  {
    id: 50,
    courseName: "Advanced Data Science",
    courseNumber: 50,
    completePercentage: 25,
  },
];

const courseProgressContent = {
  title: "সার্বিক কোর্সের অগ্রগতি",
};


export default courseProgressContent;
